### ISSUE TITLE
please post this project

### ISSUE THREAD

**Issue by World4Flix** [SaherBlueEagle/Android_RAT_APK_Version#1]
all support  :)

**Comment by SaherBlueEagle** [comment]
INSHAALLAH , it will be , soon !!

**Comment by World4Flix** [comment]
waiting <3

**Comment by Vmoserver** [comment]
Hallo sir when will you release the app

**Comment by SaherBlueEagle** [comment]
it`s now posted , build the apk and install it on phone , then estimate the local IP (192.***** ) or (((no-ip + port forward for android))) ,  and port and build the exe , then run it on PC , and on apk listen to the same port number , and to refresh connections just pull the empty list table to refresh ( tab to refresh ) , and have fun controlling your PC from your mobile phone , don`t forget to make tutorials
